---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
      version: blue
  template:
    metadata:
      name: hello-nginx
      labels:
        app: hello-nginx
        version: blue
    spec:
      containers:
      - name: nginx-container
        image: saptarshi2446/mysqlnginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
  labels:
    app: hello-nginx
spec:
  selector:
    app: hello-nginx
    version: blue
  type: NodePort
  ports:
  - nodePort: 32223
    port: 80
    targetPort: 80
